input_dir: /data/manke/sikora/oarfish_miniworkshop/oarfish_test_data
fromBam: False
phasedVcf:
sampleSheet: /data/manke/sikora/oarfish_miniworkshop/oarfish_test_data/sampleSheet.tsv
organism: hg38
correctRTA: False
num_bootstraps: 50
